# DO NOT EDIT THIS FILE
include $(dw_arm_processors_path)/Makefile.defs
dw_arm_processors.DW_arm946es.OBJS_OPT = $(LIBDIR_OPT)/DW_arm946es$(OBJSUFFIX) 
dw_arm_processors.DW_arm946es.OBJS_DBG = $(LIBDIR_DBG)/DW_arm946es$(OBJSUFFIX) 
dw_arm_processors.DW_arm946es.OBJS_UNOPT = $(LIBDIR_UNOPT)/DW_arm946es$(OBJSUFFIX) 
dw_arm_processors.DW_arm946es.USR_CFLAGS_OPT = $(dw_arm_processors.DW_arm946es.USR_CFLAGS_OPT_$(SNPS_ARCH)) $(dw_arm_processors_CFLAGS_OPT)
dw_arm_processors.DW_arm946es.USR_INCS_OPT = $(dw_arm_processors.DW_arm946es.USR_INCS_OPT_$(SNPS_ARCH)) $(dw_arm_processors_INCS_OPT)
dw_arm_processors.DW_arm946es.USR_CFLAGS_OPT_sparcOS5 =  
dw_arm_processors.DW_arm946es.USR_INCS_OPT_sparcOS5 = -I${dw_amba_ahb_path}/ -I${dw_arm_processors_aux_path}/ 
dw_arm_processors.DW_arm946es.USR_CFLAGS_OPT_gccsparcOS5 =  
dw_arm_processors.DW_arm946es.USR_INCS_OPT_gccsparcOS5 = -I${dw_amba_ahb_path}/ -I${dw_arm_processors_aux_path}/ 
dw_arm_processors.DW_arm946es.USR_CFLAGS_OPT_hp32 =  
dw_arm_processors.DW_arm946es.USR_INCS_OPT_hp32 = -I${dw_amba_ahb_path}/ -I${dw_arm_processors_aux_path}/ 
dw_arm_processors.DW_arm946es.USR_CFLAGS_OPT_linux =  
dw_arm_processors.DW_arm946es.USR_INCS_OPT_linux = -I${dw_amba_ahb_path}/ -I${dw_arm_processors_aux_path}/ 

dw_arm_processors.DW_arm946es.USR_CFLAGS_DBG = $(dw_arm_processors.DW_arm946es.USR_CFLAGS_DBG_$(SNPS_ARCH)) $(dw_arm_processors_CFLAGS_DBG)
dw_arm_processors.DW_arm946es.USR_INCS_DBG = $(dw_arm_processors.DW_arm946es.USR_INCS_DBG_$(SNPS_ARCH)) $(dw_arm_processors_INCS_DBG)
dw_arm_processors.DW_arm946es.USR_CFLAGS_DBG_sparcOS5 =  
dw_arm_processors.DW_arm946es.USR_INCS_DBG_sparcOS5 = -I${dw_amba_ahb_path}/ -I${dw_arm_processors_aux_path}/ 
dw_arm_processors.DW_arm946es.USR_CFLAGS_DBG_gccsparcOS5 =  
dw_arm_processors.DW_arm946es.USR_INCS_DBG_gccsparcOS5 = -I${dw_amba_ahb_path}/ -I${dw_arm_processors_aux_path}/ 
dw_arm_processors.DW_arm946es.USR_CFLAGS_DBG_hp32 =  
dw_arm_processors.DW_arm946es.USR_INCS_DBG_hp32 = -I${dw_amba_ahb_path}/ -I${dw_arm_processors_aux_path}/ 
dw_arm_processors.DW_arm946es.USR_CFLAGS_DBG_linux =  
dw_arm_processors.DW_arm946es.USR_INCS_DBG_linux = -I${dw_amba_ahb_path}/ -I${dw_arm_processors_aux_path}/ 

dw_arm_processors.DW_arm946es.USR_CFLAGS_UNOPT = $(dw_arm_processors.DW_arm946es.USR_CFLAGS_UNOPT_$(SNPS_ARCH)) $(dw_arm_processors_CFLAGS_UNOPT)
dw_arm_processors.DW_arm946es.USR_INCS_UNOPT = $(dw_arm_processors.DW_arm946es.USR_INCS_UNOPT_$(SNPS_ARCH)) $(dw_arm_processors_INCS_UNOPT)
dw_arm_processors.DW_arm946es.USR_CFLAGS_UNOPT_sparcOS5 =  
dw_arm_processors.DW_arm946es.USR_INCS_UNOPT_sparcOS5 = -I${dw_amba_ahb_path}/ -I${dw_arm_processors_aux_path}/ 
dw_arm_processors.DW_arm946es.USR_CFLAGS_UNOPT_gccsparcOS5 =  
dw_arm_processors.DW_arm946es.USR_INCS_UNOPT_gccsparcOS5 = -I${dw_amba_ahb_path}/ -I${dw_arm_processors_aux_path}/ 
dw_arm_processors.DW_arm946es.USR_CFLAGS_UNOPT_hp32 =  
dw_arm_processors.DW_arm946es.USR_INCS_UNOPT_hp32 = -I${dw_amba_ahb_path}/ -I${dw_arm_processors_aux_path}/ 
dw_arm_processors.DW_arm946es.USR_CFLAGS_UNOPT_linux =  
dw_arm_processors.DW_arm946es.USR_INCS_UNOPT_linux = -I${dw_amba_ahb_path}/ -I${dw_arm_processors_aux_path}/ 

dw_arm_processors.DW_arm946es.INCLUDES_OPT = $(dw_arm_processors.DW_arm946es.USR_INCS_OPT) 

dw_arm_processors.DW_arm946es.INCLUDES_DBG = $(dw_arm_processors.DW_arm946es.USR_INCS_DBG) 

dw_arm_processors.DW_arm946es.INCLUDES_UNOPT = $(dw_arm_processors.DW_arm946es.USR_INCS_UNOPT) 

dw_arm_processors.DW_arm946es.LINKS_OPT = \
	$(dw_arm_processors.DW_arm946es.LINKS_OPT_$(SNPS_ARCH))

dw_arm_processors.DW_arm946es.LINKS_OPT_sparcOS5 = -L${dw_arm_processors_path}/arm_ccm/lib-sparcOS5 -larm9
dw_arm_processors.DW_arm946es.LINKS_OPT_gccsparcOS5 = -L${dw_arm_processors_path}/arm_ccm/lib-gccsparcOS5 -larm9
dw_arm_processors.DW_arm946es.LINKS_OPT_hp32 = -L${dw_arm_processors_path}/arm_ccm/lib-hp32 -Wl,-E -larm9
dw_arm_processors.DW_arm946es.LINKS_OPT_linux = -larm9


dw_arm_processors.DW_arm946es.LINKS_DBG = \
	$(dw_arm_processors.DW_arm946es.LINKS_DBG_$(SNPS_ARCH))

dw_arm_processors.DW_arm946es.LINKS_DBG_sparcOS5 = -L${dw_arm_processors_path}/arm_ccm/lib-sparcOS5 -larm9
dw_arm_processors.DW_arm946es.LINKS_DBG_gccsparcOS5 = -L${dw_arm_processors_path}/arm_ccm/lib-gccsparcOS5 -larm9
dw_arm_processors.DW_arm946es.LINKS_DBG_hp32 = -L${dw_arm_processors_path}/arm_ccm/lib-hp32 -Wl,-E -larm9
dw_arm_processors.DW_arm946es.LINKS_DBG_linux = -larm9

dw_arm_processors.DW_arm946es.LINKS_UNOPT = \
	$(dw_arm_processors.DW_arm946es.LINKS_UNOPT_$(SNPS_ARCH))

dw_arm_processors.DW_arm946es.LINKS_UNOPT_sparcOS5 = -L${dw_arm_processors_path}/arm_ccm/lib-sparcOS5 -larm9
dw_arm_processors.DW_arm946es.LINKS_UNOPT_gccsparcOS5 = -L${dw_arm_processors_path}/arm_ccm/lib-gccsparcOS5 -larm9
dw_arm_processors.DW_arm946es.LINKS_UNOPT_hp32 = -L${dw_arm_processors_path}/arm_ccm/lib-hp32 -Wl,-E -larm9
dw_arm_processors.DW_arm946es.LINKS_UNOPT_linux = -larm9


dw_arm_processors.DW_arm946es.OVA_FILES = 

