print_sysmodel_msg:
	@echo "system model, check design not executed"

DW_arm926ejs-opt:
	@echo "system model, check design not executed"
DW_arm926ejs-debug:
	@echo "system model, check design not executed"
DW_arm926ejs-unopt:
	@echo "system model, check design not executed"


lib: lib-optimize
lib-optimize:
lib-debug:
lib-unoptimize:

clean:
	@echo "system model, check design not executed"

