# DO NOT EDIT THIS FILE
include $(dw_arm_processors_aux_path)/Makefile.defs
dw_arm_processors_aux.DW_IntrGen.OBJS_OPT = $(LIBDIR_OPT)/DW_IntrGen$(OBJSUFFIX) 
dw_arm_processors_aux.DW_IntrGen.OBJS_DBG = $(LIBDIR_DBG)/DW_IntrGen$(OBJSUFFIX) 
dw_arm_processors_aux.DW_IntrGen.OBJS_UNOPT = $(LIBDIR_UNOPT)/DW_IntrGen$(OBJSUFFIX) 
dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_OPT = $(dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_OPT_$(SNPS_ARCH)) $(dw_arm_processors_aux_CFLAGS_OPT)
dw_arm_processors_aux.DW_IntrGen.USR_INCS_OPT = $(dw_arm_processors_aux.DW_IntrGen.USR_INCS_OPT_$(SNPS_ARCH)) $(dw_arm_processors_aux_INCS_OPT)
dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_OPT_sparcOS5 = 
dw_arm_processors_aux.DW_IntrGen.USR_INCS_OPT_sparcOS5 = -I${dw_amba_ahb_path} 
dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_OPT_gccsparcOS5 = 
dw_arm_processors_aux.DW_IntrGen.USR_INCS_OPT_gccsparcOS5 = -I${dw_amba_ahb_path} 
dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_OPT_hp32 = 
dw_arm_processors_aux.DW_IntrGen.USR_INCS_OPT_hp32 = -I${dw_amba_ahb_path} 
dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_OPT_linux = 
dw_arm_processors_aux.DW_IntrGen.USR_INCS_OPT_linux = -I${dw_amba_ahb_path} 

dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_DBG = $(dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_DBG_$(SNPS_ARCH)) $(dw_arm_processors_aux_CFLAGS_DBG)
dw_arm_processors_aux.DW_IntrGen.USR_INCS_DBG = $(dw_arm_processors_aux.DW_IntrGen.USR_INCS_DBG_$(SNPS_ARCH)) $(dw_arm_processors_aux_INCS_DBG)
dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_DBG_sparcOS5 = 
dw_arm_processors_aux.DW_IntrGen.USR_INCS_DBG_sparcOS5 = -I${dw_amba_ahb_path} 
dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_DBG_gccsparcOS5 = 
dw_arm_processors_aux.DW_IntrGen.USR_INCS_DBG_gccsparcOS5 = -I${dw_amba_ahb_path} 
dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_DBG_hp32 = 
dw_arm_processors_aux.DW_IntrGen.USR_INCS_DBG_hp32 = -I${dw_amba_ahb_path} 
dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_DBG_linux = 
dw_arm_processors_aux.DW_IntrGen.USR_INCS_DBG_linux = -I${dw_amba_ahb_path} 

dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_UNOPT = $(dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_UNOPT_$(SNPS_ARCH)) $(dw_arm_processors_aux_CFLAGS_UNOPT)
dw_arm_processors_aux.DW_IntrGen.USR_INCS_UNOPT = $(dw_arm_processors_aux.DW_IntrGen.USR_INCS_UNOPT_$(SNPS_ARCH)) $(dw_arm_processors_aux_INCS_UNOPT)
dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_UNOPT_sparcOS5 = 
dw_arm_processors_aux.DW_IntrGen.USR_INCS_UNOPT_sparcOS5 = -I${dw_amba_ahb_path} 
dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_UNOPT_gccsparcOS5 = 
dw_arm_processors_aux.DW_IntrGen.USR_INCS_UNOPT_gccsparcOS5 = -I${dw_amba_ahb_path} 
dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_UNOPT_hp32 = 
dw_arm_processors_aux.DW_IntrGen.USR_INCS_UNOPT_hp32 = -I${dw_amba_ahb_path} 
dw_arm_processors_aux.DW_IntrGen.USR_CFLAGS_UNOPT_linux = 
dw_arm_processors_aux.DW_IntrGen.USR_INCS_UNOPT_linux = -I${dw_amba_ahb_path} 

dw_arm_processors_aux.DW_IntrGen.INCLUDES_OPT = $(dw_arm_processors_aux.DW_IntrGen.USR_INCS_OPT) 

dw_arm_processors_aux.DW_IntrGen.INCLUDES_DBG = $(dw_arm_processors_aux.DW_IntrGen.USR_INCS_DBG) 

dw_arm_processors_aux.DW_IntrGen.INCLUDES_UNOPT = $(dw_arm_processors_aux.DW_IntrGen.USR_INCS_UNOPT) 

dw_arm_processors_aux.DW_IntrGen.LINKS_OPT = \
	$(dw_arm_processors_aux.DW_IntrGen.LINKS_OPT_$(SNPS_ARCH))

dw_arm_processors_aux.DW_IntrGen.LINKS_OPT_sparcOS5 = 
dw_arm_processors_aux.DW_IntrGen.LINKS_OPT_gccsparcOS5 = 
dw_arm_processors_aux.DW_IntrGen.LINKS_OPT_hp32 = 
dw_arm_processors_aux.DW_IntrGen.LINKS_OPT_linux = 


dw_arm_processors_aux.DW_IntrGen.LINKS_DBG = \
	$(dw_arm_processors_aux.DW_IntrGen.LINKS_DBG_$(SNPS_ARCH))

dw_arm_processors_aux.DW_IntrGen.LINKS_DBG_sparcOS5 = 
dw_arm_processors_aux.DW_IntrGen.LINKS_DBG_gccsparcOS5 = 
dw_arm_processors_aux.DW_IntrGen.LINKS_DBG_hp32 = 
dw_arm_processors_aux.DW_IntrGen.LINKS_DBG_linux = 

dw_arm_processors_aux.DW_IntrGen.LINKS_UNOPT = \
	$(dw_arm_processors_aux.DW_IntrGen.LINKS_UNOPT_$(SNPS_ARCH))

dw_arm_processors_aux.DW_IntrGen.LINKS_UNOPT_sparcOS5 = 
dw_arm_processors_aux.DW_IntrGen.LINKS_UNOPT_gccsparcOS5 = 
dw_arm_processors_aux.DW_IntrGen.LINKS_UNOPT_hp32 = 
dw_arm_processors_aux.DW_IntrGen.LINKS_UNOPT_linux = 


dw_arm_processors_aux.DW_IntrGen.OVA_FILES = 

