print_sysmodel_msg:
	@echo "system model, check design not executed"


DW_TCMemory-opt:
	@echo "system model, check design not executed"
DW_TCMemory-debug:
	@echo "system model, check design not executed"
DW_TCMemory-unopt:
	@echo "system model, check design not executed"


DW_IntrGen-opt:
	@echo "system model, check design not executed"
DW_IntrGen-debug:
	@echo "system model, check design not executed"
DW_IntrGen-unopt:
	@echo "system model, check design not executed"

DW_HClkGen-opt:
	@echo "system model, check design not executed"
DW_HClkGen-debug:
	@echo "system model, check design not executed"
DW_HClkGen-unopt:
	@echo "system model, check design not executed"


lib: lib-optimize
lib-optimize:
lib-debug:
lib-unoptimize:
clean:
	@echo "system model, check design not executed"

