# DO NOT EDIT THIS FILE
include $(dw_arm_processors_examples_path)/Makefile.defs
dw_arm_processors_examples.DW_arm926_no_icm_example.OBJS_OPT = $(LIBDIR_OPT)/DW_arm926_no_icm_example$(OBJSUFFIX) 
dw_arm_processors_examples.DW_arm926_no_icm_example.OBJS_DBG = $(LIBDIR_DBG)/DW_arm926_no_icm_example$(OBJSUFFIX) 
dw_arm_processors_examples.DW_arm926_no_icm_example.OBJS_UNOPT = $(LIBDIR_UNOPT)/DW_arm926_no_icm_example$(OBJSUFFIX) 
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_OPT = $(dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_OPT_$(SNPS_ARCH)) $(dw_arm_processors_examples_CFLAGS_OPT)
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_OPT = $(dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_OPT_$(SNPS_ARCH)) $(dw_arm_processors_examples_INCS_OPT)
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_OPT_sparcOS5 = -DNDEBUG
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_OPT_sparcOS5 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_OPT_gccsparcOS5 = -DNDEBUG
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_OPT_gccsparcOS5 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_OPT_hp32 = -DNDEBUG
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_OPT_hp32 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_OPT_linux = -DNDEBUG
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_OPT_linux = 

dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_DBG = $(dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_DBG_$(SNPS_ARCH)) $(dw_arm_processors_examples_CFLAGS_DBG)
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_DBG = $(dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_DBG_$(SNPS_ARCH)) $(dw_arm_processors_examples_INCS_DBG)
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_DBG_sparcOS5 = -DMONITOR
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_DBG_sparcOS5 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_DBG_gccsparcOS5 = -DMONITOR
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_DBG_gccsparcOS5 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_DBG_hp32 = -DMONITOR
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_DBG_hp32 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_DBG_linux = -DMONITOR
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_DBG_linux = 

dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_UNOPT = $(dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_UNOPT_$(SNPS_ARCH)) $(dw_arm_processors_examples_CFLAGS_UNOPT)
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_UNOPT = $(dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_UNOPT_$(SNPS_ARCH)) $(dw_arm_processors_examples_INCS_UNOPT)
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_UNOPT_sparcOS5 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_UNOPT_sparcOS5 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_UNOPT_gccsparcOS5 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_UNOPT_gccsparcOS5 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_UNOPT_hp32 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_UNOPT_hp32 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_CFLAGS_UNOPT_linux = 
dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_UNOPT_linux = 

dw_arm_processors_examples.DW_arm926_no_icm_example.DEPS = $(dw_amba_ahb_path)/DW_AHB_Monitor.h $(dw_amba_ahb_path)/DW_AHB_Memory.h $(source_sc_path)/ConstGen.h $(dw_amba_ahb_path)/DW_ahb_tlm.h $(dw_amba_ahb_path)/DW_AHB_Arbiter.h $(dw_arm_processors_path)/DW_arm926ejs.h $(dw_amba_ahb_path)/DW_AHB_Decoder.h $(dw_arm_processors_aux_path)/DW_TCMemory.h $(dw_arm_processors_aux_path)/DW_IntrGen.h 
dw_arm_processors_examples.DW_arm926_no_icm_example.INCLUDES_OPT = $(dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_OPT) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_AHB_Monitor.INCLUDES_OPT) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_AHB_Memory.INCLUDES_OPT) \
	-I$(source_sc_path) $(source_sc.ConstGen.INCLUDES_OPT) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_ahb_tlm.INCLUDES_OPT) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_AHB_Arbiter.INCLUDES_OPT) \
	-I$(dw_arm_processors_path) $(dw_arm_processors.DW_arm926ejs.INCLUDES_OPT) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_AHB_Decoder.INCLUDES_OPT) \
	-I$(dw_arm_processors_aux_path) $(dw_arm_processors_aux.DW_TCMemory.INCLUDES_OPT) \
	-I$(dw_arm_processors_aux_path) $(dw_arm_processors_aux.DW_IntrGen.INCLUDES_OPT) 

dw_arm_processors_examples.DW_arm926_no_icm_example.INCLUDES_DBG = $(dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_DBG) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_AHB_Monitor.INCLUDES_DBG) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_AHB_Memory.INCLUDES_DBG) \
	-I$(source_sc_path) $(source_sc.ConstGen.INCLUDES_DBG) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_ahb_tlm.INCLUDES_DBG) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_AHB_Arbiter.INCLUDES_DBG) \
	-I$(dw_arm_processors_path) $(dw_arm_processors.DW_arm926ejs.INCLUDES_DBG) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_AHB_Decoder.INCLUDES_DBG) \
	-I$(dw_arm_processors_aux_path) $(dw_arm_processors_aux.DW_TCMemory.INCLUDES_DBG) \
	-I$(dw_arm_processors_aux_path) $(dw_arm_processors_aux.DW_IntrGen.INCLUDES_DBG) 

dw_arm_processors_examples.DW_arm926_no_icm_example.INCLUDES_UNOPT = $(dw_arm_processors_examples.DW_arm926_no_icm_example.USR_INCS_UNOPT) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_AHB_Monitor.INCLUDES_UNOPT) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_AHB_Memory.INCLUDES_UNOPT) \
	-I$(source_sc_path) $(source_sc.ConstGen.INCLUDES_UNOPT) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_ahb_tlm.INCLUDES_UNOPT) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_AHB_Arbiter.INCLUDES_UNOPT) \
	-I$(dw_arm_processors_path) $(dw_arm_processors.DW_arm926ejs.INCLUDES_UNOPT) \
	-I$(dw_amba_ahb_path) $(dw_amba_ahb.DW_AHB_Decoder.INCLUDES_UNOPT) \
	-I$(dw_arm_processors_aux_path) $(dw_arm_processors_aux.DW_TCMemory.INCLUDES_UNOPT) \
	-I$(dw_arm_processors_aux_path) $(dw_arm_processors_aux.DW_IntrGen.INCLUDES_UNOPT) 

ifndef dw_amba_ahb.DW_AHB_Monitor.msg
$(dw_amba_ahb_path)/DW_AHB_Monitor.make:
	@-echo "CCSS_ERROR_MESSAGE $(dw_amba_ahb_path)/DW_AHB_Monitor.make is missing, please regenerate the sources of model dw_amba_ahb/DW_AHB_Monitor"
include $(dw_amba_ahb_path)/DW_AHB_Monitor.make
dw_amba_ahb.DW_AHB_Monitor.msg = 1
endif
ifndef dw_amba_ahb.DW_AHB_Memory.msg
$(dw_amba_ahb_path)/DW_AHB_Memory.make:
	@-echo "CCSS_ERROR_MESSAGE $(dw_amba_ahb_path)/DW_AHB_Memory.make is missing, please regenerate the sources of model dw_amba_ahb/DW_AHB_Memory"
include $(dw_amba_ahb_path)/DW_AHB_Memory.make
dw_amba_ahb.DW_AHB_Memory.msg = 1
endif
ifndef source_sc.ConstGen.msg
$(source_sc_path)/ConstGen.make:
	@-echo "CCSS_ERROR_MESSAGE $(source_sc_path)/ConstGen.make is missing, please regenerate the sources of model source_sc/ConstGen"
include $(source_sc_path)/ConstGen.make
source_sc.ConstGen.msg = 1
endif
ifndef dw_amba_ahb.DW_ahb_tlm.msg
$(dw_amba_ahb_path)/DW_ahb_tlm.make:
	@-echo "CCSS_ERROR_MESSAGE $(dw_amba_ahb_path)/DW_ahb_tlm.make is missing, please regenerate the sources of model dw_amba_ahb/DW_ahb_tlm"
include $(dw_amba_ahb_path)/DW_ahb_tlm.make
dw_amba_ahb.DW_ahb_tlm.msg = 1
endif
ifndef dw_amba_ahb.DW_AHB_Arbiter.msg
$(dw_amba_ahb_path)/DW_AHB_Arbiter.make:
	@-echo "CCSS_ERROR_MESSAGE $(dw_amba_ahb_path)/DW_AHB_Arbiter.make is missing, please regenerate the sources of model dw_amba_ahb/DW_AHB_Arbiter"
include $(dw_amba_ahb_path)/DW_AHB_Arbiter.make
dw_amba_ahb.DW_AHB_Arbiter.msg = 1
endif
ifndef dw_arm_processors.DW_arm926ejs.msg
$(dw_arm_processors_path)/DW_arm926ejs.make:
	@-echo "CCSS_ERROR_MESSAGE $(dw_arm_processors_path)/DW_arm926ejs.make is missing, please regenerate the sources of model dw_arm_processors/DW_arm926ejs"
include $(dw_arm_processors_path)/DW_arm926ejs.make
dw_arm_processors.DW_arm926ejs.msg = 1
endif
ifndef dw_amba_ahb.DW_AHB_Decoder.msg
$(dw_amba_ahb_path)/DW_AHB_Decoder.make:
	@-echo "CCSS_ERROR_MESSAGE $(dw_amba_ahb_path)/DW_AHB_Decoder.make is missing, please regenerate the sources of model dw_amba_ahb/DW_AHB_Decoder"
include $(dw_amba_ahb_path)/DW_AHB_Decoder.make
dw_amba_ahb.DW_AHB_Decoder.msg = 1
endif
ifndef dw_arm_processors_aux.DW_TCMemory.msg
$(dw_arm_processors_aux_path)/DW_TCMemory.make:
	@-echo "CCSS_ERROR_MESSAGE $(dw_arm_processors_aux_path)/DW_TCMemory.make is missing, please regenerate the sources of model dw_arm_processors_aux/DW_TCMemory"
include $(dw_arm_processors_aux_path)/DW_TCMemory.make
dw_arm_processors_aux.DW_TCMemory.msg = 1
endif
ifndef dw_arm_processors_aux.DW_IntrGen.msg
$(dw_arm_processors_aux_path)/DW_IntrGen.make:
	@-echo "CCSS_ERROR_MESSAGE $(dw_arm_processors_aux_path)/DW_IntrGen.make is missing, please regenerate the sources of model dw_arm_processors_aux/DW_IntrGen"
include $(dw_arm_processors_aux_path)/DW_IntrGen.make
dw_arm_processors_aux.DW_IntrGen.msg = 1
endif

dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_OPT = \
	$(LIBPATHPREFIX)$(dw_amba_ahb_path)/lib-$(SNPS_ARCH) $(LINKPREFIX)dw_amba_ahb$(LIBTYPE_dw_amba_ahb_OPT)$(LINKSUFFIX) $(dw_amba_ahb_LINKS_OPT) $(dw_amba_ahb.DW_AHB_Monitor.LINKS_OPT) \
	$(dw_amba_ahb.DW_AHB_Memory.LINKS_OPT) \
	$(dw_amba_ahb.DW_ahb_tlm.LINKS_OPT) \
	$(dw_amba_ahb.DW_AHB_Arbiter.LINKS_OPT) \
	$(dw_amba_ahb.DW_AHB_Decoder.LINKS_OPT)  \
	$(LIBPATHPREFIX)$(dw_arm_processors_path)/lib-$(SNPS_ARCH) $(LINKPREFIX)dw_arm_processors$(LIBTYPE_dw_arm_processors_OPT)$(LINKSUFFIX) $(dw_arm_processors_LINKS_OPT) $(dw_arm_processors.DW_arm926ejs.LINKS_OPT)  \
	$(LIBPATHPREFIX)$(dw_arm_processors_aux_path)/lib-$(SNPS_ARCH) $(LINKPREFIX)dw_arm_processors_aux$(LIBTYPE_dw_arm_processors_aux_OPT)$(LINKSUFFIX) $(dw_arm_processors_aux_LINKS_OPT) $(dw_arm_processors_aux.DW_TCMemory.LINKS_OPT) \
	$(dw_arm_processors_aux.DW_IntrGen.LINKS_OPT)  \
	$(LIBPATHPREFIX)$(source_sc_path)/lib-$(SNPS_ARCH) $(LINKPREFIX)source_sc$(LIBTYPE_source_sc_OPT)$(LINKSUFFIX) $(source_sc_LINKS_OPT) $(source_sc.ConstGen.LINKS_OPT)  \
	$(dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_OPT_$(SNPS_ARCH))

dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_OPT_sparcOS5 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_OPT_gccsparcOS5 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_OPT_hp32 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_OPT_linux = 


dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_DBG = \
	$(LIBPATHPREFIX)$(dw_amba_ahb_path)/lib-$(SNPS_ARCH) $(LINKPREFIX)dw_amba_ahb$(LIBTYPE_dw_amba_ahb_DBG)$(LINKSUFFIX) $(dw_amba_ahb_LINKS_DBG) $(dw_amba_ahb.DW_AHB_Monitor.LINKS_DBG) \
	$(dw_amba_ahb.DW_AHB_Memory.LINKS_DBG) \
	$(dw_amba_ahb.DW_ahb_tlm.LINKS_DBG) \
	$(dw_amba_ahb.DW_AHB_Arbiter.LINKS_DBG) \
	$(dw_amba_ahb.DW_AHB_Decoder.LINKS_DBG)  \
	$(LIBPATHPREFIX)$(dw_arm_processors_path)/lib-$(SNPS_ARCH) $(LINKPREFIX)dw_arm_processors$(LIBTYPE_dw_arm_processors_DBG)$(LINKSUFFIX) $(dw_arm_processors_LINKS_DBG) $(dw_arm_processors.DW_arm926ejs.LINKS_DBG)  \
	$(LIBPATHPREFIX)$(dw_arm_processors_aux_path)/lib-$(SNPS_ARCH) $(LINKPREFIX)dw_arm_processors_aux$(LIBTYPE_dw_arm_processors_aux_DBG)$(LINKSUFFIX) $(dw_arm_processors_aux_LINKS_DBG) $(dw_arm_processors_aux.DW_TCMemory.LINKS_DBG) \
	$(dw_arm_processors_aux.DW_IntrGen.LINKS_DBG)  \
	$(LIBPATHPREFIX)$(source_sc_path)/lib-$(SNPS_ARCH) $(LINKPREFIX)source_sc$(LIBTYPE_source_sc_DBG)$(LINKSUFFIX) $(source_sc_LINKS_DBG) $(source_sc.ConstGen.LINKS_DBG)  \
	$(dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_DBG_$(SNPS_ARCH))

dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_DBG_sparcOS5 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_DBG_gccsparcOS5 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_DBG_hp32 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_DBG_linux = 

dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_UNOPT = \
	$(LIBPATHPREFIX)$(dw_amba_ahb_path)/lib-$(SNPS_ARCH) $(LINKPREFIX)dw_amba_ahb$(LIBTYPE_dw_amba_ahb_DBG)$(LINKSUFFIX) $(dw_amba_ahb_LINKS_DBG) $(dw_amba_ahb.DW_AHB_Monitor.LINKS_DBG) \
	$(dw_amba_ahb.DW_AHB_Memory.LINKS_DBG) \
	$(dw_amba_ahb.DW_ahb_tlm.LINKS_DBG) \
	$(dw_amba_ahb.DW_AHB_Arbiter.LINKS_DBG) \
	$(dw_amba_ahb.DW_AHB_Decoder.LINKS_DBG) \
	$(dw_amba_ahb.DW_AHB_Decoder.LINKS_UNOPT)  \
	$(LIBPATHPREFIX)$(dw_arm_processors_path)/lib-$(SNPS_ARCH) $(LINKPREFIX)dw_arm_processors$(LIBTYPE_dw_arm_processors_DBG)$(LINKSUFFIX) $(dw_arm_processors_LINKS_DBG) $(dw_arm_processors.DW_arm926ejs.LINKS_DBG) \
	$(dw_arm_processors.DW_arm926ejs.LINKS_UNOPT)  \
	$(LIBPATHPREFIX)$(dw_arm_processors_aux_path)/lib-$(SNPS_ARCH) $(LINKPREFIX)dw_arm_processors_aux$(LIBTYPE_dw_arm_processors_aux_DBG)$(LINKSUFFIX) $(dw_arm_processors_aux_LINKS_DBG) $(dw_arm_processors_aux.DW_TCMemory.LINKS_DBG) \
	$(dw_arm_processors_aux.DW_IntrGen.LINKS_DBG) \
	$(dw_arm_processors_aux.DW_IntrGen.LINKS_UNOPT)  \
	$(LIBPATHPREFIX)$(source_sc_path)/lib-$(SNPS_ARCH) $(LINKPREFIX)source_sc$(LIBTYPE_source_sc_DBG)$(LINKSUFFIX) $(source_sc_LINKS_DBG) $(source_sc.ConstGen.LINKS_DBG) \
	$(source_sc.ConstGen.LINKS_UNOPT)  \
	$(dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_UNOPT_$(SNPS_ARCH))

dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_UNOPT_sparcOS5 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_UNOPT_gccsparcOS5 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_UNOPT_hp32 = 
dw_arm_processors_examples.DW_arm926_no_icm_example.LINKS_UNOPT_linux = 


dw_arm_processors_examples.DW_arm926_no_icm_example.OVA_FILES = \
        $(dw_amba_ahb.DW_AHB_Monitor.OVA_FILES) \
        $(dw_amba_ahb.DW_AHB_Memory.OVA_FILES) \
        $(source_sc.ConstGen.OVA_FILES) \
        $(dw_amba_ahb.DW_ahb_tlm.OVA_FILES) \
        $(dw_amba_ahb.DW_AHB_Arbiter.OVA_FILES) \
        $(dw_arm_processors.DW_arm926ejs.OVA_FILES) \
        $(dw_amba_ahb.DW_AHB_Decoder.OVA_FILES) \
        $(dw_arm_processors_aux.DW_TCMemory.OVA_FILES) \
        $(dw_arm_processors_aux.DW_IntrGen.OVA_FILES) 

