print_sysmodel_msg:
	@echo "system model, check design not executed"


DW_arm926_example-opt:
	@echo "system model, check design not executed"
DW_arm926_example-debug:
	@echo "system model, check design not executed"
DW_arm926_example-unopt:
	@echo "system model, check design not executed"

DW_arm946_example-opt:
	@echo "system model, check design not executed"
DW_arm946_example-debug:
	@echo "system model, check design not executed"
DW_arm946_example-unopt:
	@echo "system model, check design not executed"



lib: lib-optimize
lib-optimize:
lib-debug:
lib-unoptimize:
clean:
	@echo "system model, check design not executed"

